# 1. Database Connection (Neon Cloud)
spring.datasource.url=jdbc:postgresql://ep-snowy-band-ag6ixs41-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FIrw5i9BUSdY

# 2. Hibernate / JPA (Auto-create tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Server Port
server.port=8080